@startuml

class Employee{

}

class Shift{

}

class ShiftLeader{

}

class ShiftWorker{

}

class Workstation{

}

class Working{

}

Shift "1" -- "*" ShiftLeader : < is Leader of
Shift "1" -- "*" ShiftWorker : > has

ShiftLeader --|> Employee
ShiftWorker --|> Employee

ShiftWorker "*" -- "*" Workstation : > works at

(ShiftWorker,Workstation) .. Working

@enduml